apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "postgresql:5432"
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.postgresql.database }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.postgresql.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.postgresql.password }}
          resources:
            requests:
              memory: {{ .Values.wordpress.resources.requests.memory }}
              cpu: {{ .Values.wordpress.resources.requests.cpu }}
            limits:
              memory: {{ .Values.wordpress.resources.limits.memory }}
              cpu: {{ .Values.wordpress.resources.limits.cpu }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
